### ISSUE TITLE
Action Text Alignment

### ISSUE THREAD

**Issue by dongel6** [DominicMDev/DMActionController#1]
Hey. I really like the look of the Action controller. I am creating an app in Arabic that has text aligned to the right. How can I do that? I tried to change DMActionView line 53, text alignment, but to no avail. Thank you

**Comment by DominicMDev** [comment]
I will be pulling the "appearance" branch into "master" soon. Try your change on that branch, if that doesn't work for you I may need more info about how you would like it to be displayed.

**Comment by dongel6** [comment]
Sorry for wasting your time. My change perform what I need. Just forgot to clean the build files.
